- UniversalAlgebra/Algebras/Basic.lagda
- UniversalAlgebra/Algebras/Congruences.lagda
- UniversalAlgebra/Algebras/Products.lagda
- UniversalAlgebra/Homomorphisms/Basic.lagda
- UniversalAlgebra/Homomorphisms/HomomorphicImages.lagda
- UniversalAlgebra/Homomorphisms/Isomorphisms.lagda
- UniversalAlgebra/Homomorphisms/Noether.lagda
- UniversalAlgebra/Overture/Equality.lagda
- UniversalAlgebra/Overture/FunExtensionality.lagda
- UniversalAlgebra/Overture/Inverses.lagda
- UniversalAlgebra/Overture/Lifts.lagda
- UniversalAlgebra/Overture/Preliminaries.lagda
- UniversalAlgebra/Relations/Continuous.lagda
- UniversalAlgebra/Relations/Discrete.lagda
- UniversalAlgebra/Relations/Extensionality.lagda
- UniversalAlgebra/Relations/Quotients.lagda
- UniversalAlgebra/Relations/Truncation.lagda
- UniversalAlgebra/Subalgebras/Subalgebras.lagda
- UniversalAlgebra/Subalgebras/Subuniverses.lagda
- UniversalAlgebra/Terms/Basic.lagda
- UniversalAlgebra/Terms/Operations.lagda
- UniversalAlgebra/Varieties/EquationalLogic.lagda
- UniversalAlgebra/Varieties/FreeAlgebras.lagda
- UniversalAlgebra/Varieties/Preservation.lagda
- UniversalAlgebra/Varieties/Varieties.lagda
Still, there is quite a bit of room for improvement.
> completed rough translation to standard Agda

- UniversalAlgebra/Algebras/Basic.lagda
- UniversalAlgebra/Algebras/Products.lagda
- UniversalAlgebra/Homomorphisms/Isomorphisms.lagda
- UniversalAlgebra/UniversalAlgebra.agda-lib
- UniversalAlgebra/Varieties/EquationalLogic.lagda
- UniversalAlgebra/Varieties/FreeAlgebras.lagda
- UniversalAlgebra/Varieties/Preservation.lagda
- UniversalAlgebra/Varieties/Varieties.lagda
(last commit before dependency reorganization)
> remove remaining MGS dependencies

- README.md
- UniversalAlgebra/Preface.lagda
Minor edits to adapt to the fact that the library doesn't use Type Topology.  Remove installation instructions (for now).
> Adjust preface

- UniversalAlgebra/Algebras/Products.lagda
- UniversalAlgebra/Homomorphisms/Basic.lagda
- UniversalAlgebra/Homomorphisms/HomomorphicImages.lagda
- UniversalAlgebra/Homomorphisms/Noether.lagda
- UniversalAlgebra/Overture/Inverses.lagda
- UniversalAlgebra/Overture/Preliminaries.lagda
- UniversalAlgebra/Relations/Extensionality.lagda
- UniversalAlgebra/Relations/Truncation.lagda
- UniversalAlgebra/Subalgebras/Subalgebras.lagda
- UniversalAlgebra/Subalgebras/Subuniverses.lagda
- UniversalAlgebra/Terms/Basic.lagda
- UniversalAlgebra/Terms/Operations.lagda
- UniversalAlgebra/Varieties/EquationalLogic.lagda
- UniversalAlgebra/Varieties/FreeAlgebras.lagda
- UniversalAlgebra/Varieties/Preservation.lagda
- UniversalAlgebra/Varieties/Varieties.lagda
Simplify definition of Inverse.  PR#12 should be checked in first, as this one was (incorrectly) made to depend on it. It could be split if wanted.
> Overture inverse

- UniversalAlgebra/Algebras/Congruences.lagda
- UniversalAlgebra/Homomorphisms/Basic.lagda
- UniversalAlgebra/Homomorphisms/Noether.lagda
- UniversalAlgebra/Relations/Quotients.lagda
make IsBlock into a record, to reduce the abuse of Sigma types for everything.
It would be better still to make the condition even less extensional, but Agda becomes quite unhappy later, so punt on that part for now.
> Use a record for IsBlock.

- UniversalAlgebra/Homomorphisms/Basic.lagda
- UniversalAlgebra/Varieties/FreeAlgebras.lagda
This PR just resolves an issue caused by a mistake I made when resolving an earlier merge conflict.
> fix previous merge conflict resolution

- UniversalAlgebra/Algebras/Basic.lagda
- UniversalAlgebra/Algebras/Congruences.lagda
- UniversalAlgebra/Algebras/Products.lagda
- UniversalAlgebra/Homomorphisms/Basic.lagda
- UniversalAlgebra/Homomorphisms/HomomorphicImages.lagda
- UniversalAlgebra/Homomorphisms/Isomorphisms.lagda
- UniversalAlgebra/Homomorphisms/Noether.lagda
- UniversalAlgebra/Overture/Inverses.lagda
- UniversalAlgebra/Overture/Preliminaries.lagda
- UniversalAlgebra/Relations/Continuous.lagda
- UniversalAlgebra/Relations/Discrete.lagda
- UniversalAlgebra/Relations/Extensionality.lagda
- UniversalAlgebra/Relations/Quotients.lagda
- UniversalAlgebra/Relations/Truncation.lagda
- UniversalAlgebra/Subalgebras/Subalgebras.lagda
- UniversalAlgebra/Subalgebras/Subuniverses.lagda
- UniversalAlgebra/Terms/Basic.lagda
- UniversalAlgebra/Terms/Operations.lagda
- UniversalAlgebra/Varieties/EquationalLogic.lagda
- UniversalAlgebra/Varieties/FreeAlgebras.lagda
- UniversalAlgebra/Varieties/Preservation.lagda
- UniversalAlgebra/Varieties/Varieties.lagda
global 'variable's are bad style. Make them private/local to each file.
> Move variable declarations into each of the files

- UniversalAlgebra/Relations/Extensionality.lagda
- UniversalAlgebra/Varieties/EquationalLogic.lagda
- UniversalAlgebra/Varieties/FreeAlgebras.lagda
- UniversalAlgebra/Varieties/Preservation.lagda
trim down Extensionality (remove discussion best left to UALib). Make funext use even more obvious by reducing one level of indirection to it.
> Edits to Relations.Extensionality and related

- UniversalAlgebra/Algebras/Basic.lagda
- UniversalAlgebra/Algebras/Products.lagda
- UniversalAlgebra/Homomorphisms/Basic.lagda
- UniversalAlgebra/Homomorphisms/HomomorphicImages.lagda
- UniversalAlgebra/Homomorphisms/Isomorphisms.lagda
- UniversalAlgebra/Overture/Preliminaries.lagda
- UniversalAlgebra/Relations.lagda
- UniversalAlgebra/Relations/Continuous.lagda
- UniversalAlgebra/Relations/Discrete.lagda
- UniversalAlgebra/Relations/Extensionality.lagda
- UniversalAlgebra/Relations/Truncation.lagda
- UniversalAlgebra/Subalgebras/Subalgebras.lagda
- UniversalAlgebra/Varieties/Basic.lagda
- UniversalAlgebra/Varieties/Closure/H.lagda
- UniversalAlgebra/Varieties/Closure/P.lagda
- UniversalAlgebra/Varieties/Closure/S.lagda
- UniversalAlgebra/Varieties/Closure/V.lagda
- UniversalAlgebra/Varieties/EquationalLogic.lagda
- UniversalAlgebra/Varieties/Preservation.lagda
- UniversalAlgebra/agda-algebras-everything.lagda
- UniversalAlgebra/agda-stdlib-imports.lagda
This changes a few things about the API, e.g, change order of arguments of Op type.
> refactoring and other improvements

- UniversalAlgebra/Homomorphisms/Noether.lagda
- UniversalAlgebra/Relations/Discrete.lagda
- UniversalAlgebra/Relations/Extensionality.lagda
- UniversalAlgebra/Structures/Basic.lagda
- UniversalAlgebra/Varieties/FreeAlgebras.lagda
- UniversalAlgebra/agda-algebras-everything.lagda
remove a couple of unnecessary invocations of function extensionality
> minor improvements

- UniversalAlgebra/Algebras/Basic.lagda
- UniversalAlgebra/Algebras/Congruences.lagda
- UniversalAlgebra/Demos/TYPES2021-extrashort.lagda
- UniversalAlgebra/Demos/TYPES2021-short.lagda
- UniversalAlgebra/Demos/TYPES2021-shortimports.agda
- UniversalAlgebra/Demos/TYPES2021.lagda
- UniversalAlgebra/Relations/Continuous.lagda
- UniversalAlgebra/Relations/Truncation.lagda
- UniversalAlgebra/Structures/AsRecords.lagda
- UniversalAlgebra/Structures/congruences.lagda
- UniversalAlgebra/Structures/products.lagda
- UniversalAlgebra/Varieties/Basic.lagda
- UniversalAlgebra/Varieties/FreeAlgebras.lagda
- UniversalAlgebra/agda-algebras-everything.lagda
Not sure that these monolithic demo files belong in the main repository... maybe we'll delete them later.
> Contexts for terms

- README.md
- UniversalAlgebra/Algebras/Congruences.lagda
- UniversalAlgebra/Algebras/Setoid.lagda
- UniversalAlgebra/Algebras/SetoidCongruences.lagda
- UniversalAlgebra/Relations/Discrete.lagda
- UniversalAlgebra/Terms/Setoid.lagda
- UniversalAlgebra/Varieties/EquationalLogic.lagda
- UniversalAlgebra/Varieties/FreeAlgebras.lagda
- UniversalAlgebra/agda-algebras-everything.lagda
This was already part of the products-for-setoids merge request, but just to be sure...
> Congruences for setoids

- UniversalAlgebra/Algebras/Setoid.lagda
- UniversalAlgebra/Structures/Entailment.lagda
- UniversalAlgebra/Structures/Graphs.lagda
- UniversalAlgebra/Structures/Terms.lagda
- UniversalAlgebra/Terms/Basic.lagda
- UniversalAlgebra/Varieties/EquationalLogic.lagda
- UniversalAlgebra/agda-algebras-everything.lagda
- UniversalAlgebra/agda-stdlib-imports.lagda
split terms and entailment off into their own modules
> reorg and cosmetic changes

- UniversalAlgebra/GaloisConnections/Basic.lagda
- UniversalAlgebra/GaloisConnections/Properties.lagda
Generalize universe levels to be (almost) as general as the code Jacques posted on zulip.
> Galois connections

- UniversalAlgebra/GaloisConnections/Basic.lagda
- UniversalAlgebra/GaloisConnections/Properties.lagda
Also remove the universe-non-polymorphic versions
> replace the place holder names (Foo/Bar) with arrows

- UniversalAlgebra/ClosureSystems/Basic.lagda
- UniversalAlgebra/ClosureSystems/Properties.lagda
Some of these things should also be in stdlib. I'll try to make some PRs there - but if you want credit for contributing to the larger community, you should too!
> just making things prettier.

- UniversalAlgebra/GaloisConnections/Basic.lagda
- UniversalAlgebra/agda-algebras-everything.lagda
fix level names. Fix agda-algebra-everything too as exports changed.
> Fix issues from PR #61

- UniversalAlgebra/Structures/Examples.lagda
- UniversalAlgebra/Structures/Graphs/0Graphs.lagda
- UniversalAlgebra/Structures/Graphs/Basic.lagda
- UniversalAlgebra/Structures/Homs/Records.lagda
- UniversalAlgebra/Structures/Records.lagda
- UniversalAlgebra/agda-algebras-everything.lagda
**move signature examples** to separate examples file
+ add example of finite purely algebraic structure (3-element meet semilattice)
+ add example of finite purely relational structure (NAE-3-SAT relation over {0,1})
> Move examples to separate file and add examples of finite structures

- UniversalAlgebra/Structures/Congruences/Records.lagda
- UniversalAlgebra/Structures/Examples.lagda
- UniversalAlgebra/Structures/Graphs/0Graphs.lagda
- UniversalAlgebra/Structures/Graphs/Basic.lagda
- UniversalAlgebra/Structures/Homs/Basic.lagda
- UniversalAlgebra/Structures/Homs/Records.lagda
- UniversalAlgebra/Structures/Products/Records.lagda
- UniversalAlgebra/Structures/Records.lagda
- UniversalAlgebra/Structures/Terms/Basic.lagda
- UniversalAlgebra/Structures/Terms/Entailment.lagda
- UniversalAlgebra/agda-algebras-everything.lagda
make the definitions fully universe-polymorphic
> improve definitions related to general structures

- UniversalAlgebra/Complexity/CSP.lagda
fixes something broken by the reorg-terms PR
> Reorg terms

- UniversalAlgebra/Relations/Discrete.lagda
- UniversalAlgebra/Structures/Substructures/Basic.lagda
- UniversalAlgebra/Structures/Substructures/Substructures.lagda
- UniversalAlgebra/agda-algebras-everything.lagda
plus
+ (bugfix) Structures.Substructures.Subuniverses
+ (add) Substructures definitions to agda-algebras-everything
> initial commit of Structures.Substructures.Substructures module

- UniversalAlgebra/Algebras.lagda
- UniversalAlgebra/Algebras/Setoid.lagda
- UniversalAlgebra/Complexity.lagda
- UniversalAlgebra/Foundations.lagda
- UniversalAlgebra/GaloisConnections.lagda
- UniversalAlgebra/Homomorphisms.lagda
- UniversalAlgebra/Homomorphisms/Setoid.lagda
- UniversalAlgebra/Overture.lagda
- UniversalAlgebra/Relations.lagda
- UniversalAlgebra/Structures.lagda
- UniversalAlgebra/Structures/Sigma.lagda
- UniversalAlgebra/Structures/Substructures.lagda
- UniversalAlgebra/Structures/Terms.lagda
- UniversalAlgebra/Subalgebras/Setoid.lagda
- UniversalAlgebra/UniversalAlgebra.lagda
- UniversalAlgebra/Varieties.lagda
- UniversalAlgebra/Varieties/Setoid.lagda
- UniversalAlgebra/agda-algebras-everything.lagda
Nothing significant changes.
Merely adding missing Submodule parent files, each of which imports all subsubmodules of the given submodule.
> organize submodules and add missing parent modules

- src/agda-algebras.lagda
> Html tex make

- doc/TYPES2021/Demos/HSP.tex
- doc/TYPES2021/agda-hsp.tex
- doc/TYPES2021/agda.sty
- src/Demos/HSP.lagda
- src/Overture/Inverses.lagda
- src/Varieties/Func/Preservation.lagda
- src/Varieties/Func/Properties.lagda
Almost done working on it... but looking forward to Jacques' feedback.
> a few more improvements on draft of TYPES2021 submission

- README.md
- src/Demos/HSP.lagda
fix a problem with this recently merged PR, and update README.md
> Major reorganization

- src/Base.lagda
- src/Base/Overture.lagda
- src/Preface.lagda
- src/agda-algebras.lagda
minor documentation improvement
> document organization

- src/agda-algebras.lagda
> fix broken link

- doc/TYPES2021/Demos/HSP.tex
- doc/TYPES2021/agda-hsp.tex
- doc/TYPES2021/referee/report-summary.md
- doc/TYPES2021/ualib_refs.bib
- doc/TYPES2021/wjd.sty
- src/Demos/HSP.lagda
(also added report-summary.md where we can keep track of what's left to do)
> made some of the easy fixes requested by reviewers

- src/Demos/HSP.lagda
> fix the paragraph on setoid, and remove the 'ever'.

- doc/TYPES2021/referee/report-summary.md
> closes issue #190

- doc/TYPES2021/referee/report-summary.md
> closes issue #200

- doc/TYPES2021/referee/report-summary.md
- src/Demos/HSP.lagda
just two remain, I think, marked by XXXXX in report-summary.md
> finished handling most of the remaining issues

- doc/TYPES2021/referee/report-summary.md
- src/Demos/HSP.lagda
Deals with the 'XXXX' part. There is one more 'To Do' for Ref 3.
> comment about quotients

- doc/TYPES2021/referee/report-summary.md
- doc/TYPES2021/unixode.sty
- src/Demos/HSP.lagda
Just one stage left: final proofread!
> I think this takes care of all the ref issues and responses

- .gitignore
- doc/TYPES2021/acknowledgments.tex
- src/Demos/HSP.lagda
> Acknowledgements, spacing, one ref comment

- src/Demos/HSP.lagda
Still have to make sure text describes code in the latter sections.  (I'm quite sure there are still sentences referring to the entailment type.) I'll get to that after dinner.
> cleaned up some code; made proofs clearer (to me)

- doc/TYPES2021/acknowledgments.tex
- src/Demos/HSP.lagda
...sorry, many changes were required to get the text and revised proof to line up.
> I think we're finally done.

- src/Demos/HSP.lagda
This translates `HSP.lagda` from LaTeX to Markdown so it will look better on web pages.
> update HSP.lagda for html (instead of tex)

- src/Base/Varieties/Invariants.lagda
- src/agda-algebras-everything.lagda
minor bug-fix... I'll merge this myself.
> (bugfix) Algebra type with two args is deprecated

- agda-algebras.agda-lib
- src/Base/Adjunction/Closure.lagda
- src/Setoid/Algebras/Basic.lagda
- src/Setoid/Functions/Basic.lagda
- src/Setoid/Functions/Bijective.lagda
- src/Setoid/Functions/Injective.lagda
- src/Setoid/Functions/Inverses.lagda
- src/Setoid/Functions/Surjective.lagda
- src/Setoid/Homomorphisms/Factor.lagda
- src/Setoid/Homomorphisms/HomomorphicImages.lagda
- src/Setoid/Homomorphisms/Isomorphisms.lagda
- src/Setoid/Homomorphisms/Properties.lagda
- src/Setoid/Subalgebras/Properties.lagda
- src/Setoid/Subalgebras/Subuniverses.lagda
- src/Setoid/Terms/Basic.lagda
- src/Setoid/Varieties/FreeAlgebras.lagda
- src/Setoid/Varieties/Properties.lagda
(Many of the improvements were implemented a while ago but I forgot to commit them.)
> old improvements plus refactoring for stdlib 1.7.2
